### ISSUE TITLE
Running build command many times on_pre_save

### ISSUE THREAD

**Issue by jackysee** [twolfson/sublime-hooks#10]
I have these in my project setting:
```
{
  "settings":{
    "on_pre_save_project": [
      {
        "command": "build",
        "scope": "window"
      }
    ]
  }, 
  "build_systems": [
    {
      "name": "my_script",
      "cmd": "node script.js $file",
      "working_dir": "c:\\workspace\\app",
      "selector": "source.js"
    }
  ]
}
```

The script is a dead simple node script
```js
console.log(process.argv);
```

The build system works when I press `F7` on `.js` file. The console would immediately appear.  But when I save the file, my computer would go busy for a while and finally finish the job, showing the console.

If I check the dev console, I would found:
```
Running node script.js c:\workspace\app\src\app.js
Running node script.js c:\workspace\app\src\app.js
Running node script.js c:\workspace\app\src\app.js
Running node script.js c:\workspace\app\src\app.js
....(repeated for so many times)
```

I don't know if there is any thing required to return from the `on_pre_save` hook?

**Comment by twolfson** [comment]
I'm not sure what would cause this. Maybe close/re-open as it might have bound the plugin multiple times (although it should only bind 1 hook per view). We've verified that it only runs once previously via a hook which hits an HTTP server which logs a message:

https://github.com/twolfson/dotfiles/blob/2016.1231.1837/.config/sublime-text-3/Packages/User/Preferences.sublime-settings#L22-L35

**Comment by jackysee** [comment]
If using `on_post_save`, it would only trigger once. So it's event specific?

**Comment by twolfson** [comment]
I don't think so -- I think it's Sublime Text persisting old bindings. Try quitting + restarting Sublime Text to see if the problem persists. If it does, maybe try switching to `post_save`?

**Comment by jackysee** [comment]
The problem is the same after restart. I notice that the file has also been saved so many time (from webpack watcher). My plan is to run some code formatting, so I think `pre_save` is more suitable.
