### ISSUE TITLE
Getting the file path being saved?

### ISSUE THREAD

**Issue by monovertex** [twolfson/sublime-hooks#11]
I want to run an external command when a certain file type is saved. I know how to handle the file type part, as well as the external command part. What I'm unsure of, however, is how to get the path of the file in the view being saved, so that I may pass it to that external command.

Am I missing something obvious?

**Comment by twolfson** [comment]
Our library doesn't do anything special for Sublime Text commands. As a result, the arguments that you receive for a Sublime Text command are the same regardless of where they're invoked from

For example, a `WindowCommand` only receives the arguments for the command itself when invoked via shortcut/similar:

https://www.sublimetext.com/docs/3/api_reference.html#sublime_plugin.WindowCommand

```python
run(*args, **kwargs)
```

The normal way to retrieve the active view and its resulting filepath via Sublime Text is:

```python
import sublime
active_view = sublime.active_window().active_view()
active_view.file_name() # /home/todd/github/path/to/file.txt
```

**Comment by monovertex** [comment]
Thanks for the details!
