### ISSUE TITLE
How do I run eslint on file save

### ISSUE THREAD

**Issue by MarksCode** [twolfson/sublime-hooks#12]
[Sublime ESLint package](https://packagecontrol.io/packages/ESLint) lets you run the linter by using the shortcut `Ctrl + Option + e`. What do I add as the "command" in my "on_post_save_user" to achieve this?

**Comment by twolfson** [comment]
The short answer is look in the files for said package and find the
shortcuts file. If this is using a higher level package like Sublime
Linter, then you'll have to look there

Once you've found the proper shortcuts file, find the desired keystroke.
Use its command/arguments used for your desired hook

For what it's worth, this command can also be tested/run directly via
Sublime Text's console (Ctrl+`) using sublime.run_command (or on
active_window/view depending on scope)

If you'd like a more direct example, let me know
