### ISSUE TITLE
Post-save hook not running in project scope

### ISSUE THREAD

**Issue by nk9** [twolfson/sublime-hooks#14]
I have a command which I would like to run whenever a file is saved in my project. I believe I got it set up and working… but it's not working now. I've tried replacing my command with `select_all`, to simplify matters, but that didn't help. Here's the contents of the file `./Just.sublime-project` in the root of my project:

```js
{
	"folders":
	[
		{
			"path": "."
		}
	],
	"settings": {
		"on_post_save_project": [
			  {
			    "command": "select_all"
			  }
		]
	}
}
```

Reopening the project and restarting Sublime doesn't help.

I know Hooks is installed and working because when I put this in my user settings, `select_all` is run as soon as a file is saved, regardless of project:

*~/Library/Application Support/Sublime Text/Packages/User/Preferences.sublime-settings*
```js
{
// other settings...
  "on_post_save_user": [
    {
      "command": "select_all"
    }
  ]
}
```

Versions:
- Sublime Text: 4143
- Hooks: 0.3.2

Is there a Hooks debug flag I can set to get some idea of what's going on?

**Comment by twolfson** [comment]
Huh, strange. We don't have any debug flags set up.

In this case, I usually would remove the Package Control installed version, install the `git` based version, and start adding `print()` inside that.

Let me first see if I can reproduce though. I haven't touched this code in a while, so it's possible the Project layer lost support somehow.

**Comment by twolfson** [comment]
Alright, so I just created a fresh Project and verified the post-save hook is loading indeed =/

```json
{
	"folders":
	[
		{
			"path": "github/twolfson.com"
		}
	],
	"settings": {
		"on_post_save_project": [
			{
				"command": "select_all",
			}
		],
	}
}
```

**Comment by twolfson** [comment]
The only thing that looks odd in your setup is `path` is `.`, which makes me think it'd load `$HOME` (that's what mine does).

Other than that, if I take what you pasted, it does work for me =/ I'm also on Sublime Text 4143

If you want to poke deeper in `sublime-hooks`, the workflow for local development would be:

- Remove Sublime Hooks from Package Control
- Navigate to Sublime Text's User folder
- Clone our repo there
- Start adding `print()` to debug
- View Sublime Text Console (Ctrl+`) for messages

Alternatively, `sublime-hooks` is very very short, so you might be able to sanity check various parts in the console instead

https://github.com/twolfson/sublime-hooks/blob/0.3.2/hooks.py

For example, I might dump the `view` settings to verify the `project` settings are being loaded. Entering the following in the Sublime Text Console (Ctrl+`) should get you that (i.e. expect to see an `on_post_save_project`)

```python
from pprint import pprint; pprint(view.settings().to_dict())
```

https://www.sublimetext.com/docs/api_reference.html#sublime.View

https://www.sublimetext.com/docs/api_reference.html#sublime.Settings

**Comment by nk9** [comment]
Thanks for looking into this. When I open a file in my project and run the `to_dict` command above, I get a list which **does not** include the `on_post_save_project` setting. Of course, when I remove the project setting and instead put `on_post_save_user` in my user settings, the hook appears. So it looks like this may not be anything to do with the Hooks plugin. Rather, my `.sublime-project` isn't working for some reason.

**Comment by nk9** [comment]
OOOOOOOK, I have figured out the problem. I was opening the folder containing my `.sublime-project` file using File > Open…. This will mostly not work! Instead, you have to use the Project > Open Project… item and select the `.sublime-project` file. THEN the window opens, looking exactly the same as if you'd opened the folder, but this time it parses the `.sublime-project` file and sets up the project according to the settings saved there.

This presmuably also explains why sometimes I would open the folder and Sublime would open a blank window, without even showing the sidebar. It was getting confused between these two window states, project and folder.

Here's [a discussion](https://forum.sublimetext.com/t/project-settings-file/8147/2) of why this dichotomy exists, which led me to learn about the rather hidden "Open Project…" menu item.

**Comment by twolfson** [comment]
Ahh, that'd do it. Sad you had to learn about that the hard way x_x I too went through that process at one point =/

Fwiw, the "Quick Switch Project" shortcut (under Project menu) makes toggling between folders quite easily =) (Ctrl+Cmd+P on macOS)

**Comment by nk9** [comment]
FWIW, I think the current situation is pretty unclear. I [filed a bug](https://github.com/sublimehq/sublime_text/issues/5819) about it. Here's hoping ST improves this!
