### ISSUE TITLE
Documentation on command scope.

### ISSUE THREAD

**Issue by nitecon** [twolfson/sublime-hooks#7]
Based on documentation it seems to indicate that a command is in fact a sublime text command and not a command for the command line to be executed.  Can this be clarified and also is there a way to trigger a command line execution via the hooks?  Ex: /bin/bash --login -c "foobar" by using the hooks plugin?

**Comment by twolfson** [comment]
That is correct, this is for Sublime Text's window/view commands. I'm not sure how much more we can clarify with terms like "Sublime command" and `select_all`; I don't believe there are any parallels on the CLI for that.

For your needs, you can invoke any other Sublime Text command via this plugin (e.g. one installed by a plugin). There are a lot of different plugins that do this in different ways:
- https://packagecontrol.io/packages/Shell%20Exec
- https://packagecontrol.io/packages/Console%20Exec

Once you have chosen and installed the one you want. Then, we can set up a hook to run their commands. For example, here is a hook that runs Shell Exec's run:

```
"on_post_save_user": [
  "command": "shell_exec_open",
  "args": {
    "command": "/bin/bash --login -c \"foobar\""
  }
]
```

More notes on parameters can be found here: https://github.com/twolfson/sublime-hooks/tree/0.3.2#documentation

**Comment by nitecon** [comment]
What you mentioned in the ticket is exactly what I was looking for.  By the generic name of hooks for the plugin name I expected it would be able to do whatever hooks whether CLI / sublime.  And perhaps triggering a CLI / shell "command" would just be a different arg etc.  Thanks for the clarification though.

**Comment by mconigliaro** [comment]
Do we actually need an additional package for this? The [command reference](http://docs.sublimetext.info/en/latest/reference/commands.html) lists a built-in [exec](http://docs.sublimetext.info/en/latest/reference/build_systems/exec.html) command which is supposedly capable of running arbitrary shell commands. I think this should work according to the documentation, but it doesn't, and I haven't figured out why yet... 

```
{
  "on_post_save_language": [
    {
      "command": "exec",
      "args": {
        "shell_cmd": "/usr/bin/touch /tmp/test",
      }
    }
  ]
}
```

**Comment by twolfson** [comment]
Ah, interesting. I've never seen `exec` before so maybe it will work. To troubleshoot a setup, I'd recommend figuring out the command normally in the Sublime Text console (ctrl+`)

That will help you determine what the scope needs to be (e.g. view, window, app)

https://github.com/twolfson/sublime-hooks/blob/0.3.2/hooks.py#L29-L47

```python
# view
sublime.active_window().active_view().run_command('exec', {'shell_cmd': '/usr/bin/touch /tmp/test'})
# window
sublime.active_window().run_command('exec', {'shell_cmd': '/usr/bin/touch /tmp/test'})
# app
sublime.run_command('exec', {'shell_cmd': '/usr/bin/touch /tmp/test'})
```

**Comment by mconigliaro** [comment]
@twolfson that 2nd command worked when I ran it from the sublime console. So I guess I was just missing the `scope` option:

```
{
  "on_post_save_language": [
    {
      "command": "exec",
      "scope": "window",
      "args": {
        "shell_cmd": "touch /tmp/test"
      }
    }
  ]
}
```

Now I get a little status window that says "[Finished in 0.1s]" every time it runs. Any ideas how to silence that? The `exec` documentation mentions a `quiet` option, but that doesn't seem to help.

**Comment by twolfson** [comment]
Wonderful! Glad to hear it was a simple tweak

I think the window is an artifact of the build system. I haven't worked with it much for the same reason (much more prefer a separate terminal window). I'd say keep on playing with settings or consider switching to another package for now and coming back later

**Comment by mconigliaro** [comment]
@twolfson I just found this: https://forum.sublimetext.com/t/how-do-i-remove-or-hide-finished-in-0-4s-in-console-when-running-code/32224/4

I'm not seeing the same behavior they're reporting when using the `quiet` option, but setting `show_panel_on_build` to `false` in my global preferences seems to work for now.

Thanks for the help!
