### ISSUE TITLE
Add ability to run shell commands

### ISSUE THREAD

**Issue by cujomalainey** [twolfson/sublime-hooks#9]
A simple change that would be awesome would be the ability to run shell commands. An example use case would be for files to be pushed remotely on any save.

**Comment by twolfson** [comment]
Unfortunately, that's not so simple; there are platform inconsistencies to worry about (e.g. which shell to use (if we need pipe support), setting environment variables). However, you should be able to use this plugin with another one that handles execution of commands. For example:

- Run Sublime's existing build system
- ShellCommand plugin
    - Hook would look like: https://github.com/markbirbeck/sublime-text-shell-command/tree/v0.16.0#run-a-specific-command
- Shell Exec plugin
    - Hook would look like: https://github.com/gbaptista/sublime-3-shell-exec/tree/0.0.10#git
